//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthMSModelsLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\WHSMPERSAUTH.mdf;Integr" +
            "ated Security=True;User Instance=True")]
        public string WHSMPERSAUTHConnectionString {
            get {
                return ((string)(this["WHSMPERSAUTHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\VS2010程序\\AuthModelManage\\AuthModelMa" +
            "nage\\App_Data\\WHSMPERSAUTH.mdf;Integrated Security=True;User Instance=True")]
        public string WHSMPERSAUTHConnectionString1 {
            get {
                return ((string)(this["WHSMPERSAUTHConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\VS2010程序\\AuthMS\\AuthMS\\App_Data\\WHSM" +
            "PERSAUTH.mdf;Integrated Security=True;User Instance=True")]
        public string WHSMPERSAUTHConnectionString2 {
            get {
                return ((string)(this["WHSMPERSAUTHConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\综合发布平台\\ComPublishWeb\\ComPublishWeb\\C" +
            "omPublishWeb\\App_Data\\WHSMPERSAUTH.mdf;Integrated Security=True;Connect Timeout=" +
            "30;User Instance=True")]
        public string WHSMPERSAUTHConnectionString3 {
            get {
                return ((string)(this["WHSMPERSAUTHConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\VS2010\\Myproject\\Project\\卢哥\\ComPubli" +
            "shWeb_主平台_8_5\\ComPublishWeb\\App_Data\\WHSMPERSAUTH.mdf;Integrated Security=True;U" +
            "ser Instance=True")]
        public string WHSMPERSAUTHConnectionString4 {
            get {
                return ((string)(this["WHSMPERSAUTHConnectionString4"]));
            }
        }
    }
}
