#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreLibrary.Models.Account
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WHSMPERSAUTH")]
	public partial class NewUserDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_User(T_User instance);
    partial void UpdateT_User(T_User instance);
    partial void DeleteT_User(T_User instance);
    partial void InsertT_Department(T_Department instance);
    partial void UpdateT_Department(T_Department instance);
    partial void DeleteT_Department(T_Department instance);
    #endregion
		
		public NewUserDataDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WHSMPERSAUTHConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NewUserDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewUserDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewUserDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewUserDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_User> T_User
		{
			get
			{
				return this.GetTable<T_User>();
			}
		}
		
		public System.Data.Linq.Table<T_Department> T_Department
		{
			get
			{
				return this.GetTable<T_Department>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_User")]
	public partial class T_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _Password;
		
		private string _UserName;
		
		private string _PID;
		
		private string _IDNo;
		
		private string _DepNO;
		
		private string _DepSectionNO;
		
		private string _SexNo;
		
		private long _CardNo;
		
		private long _AccountNo;
		
		private string _IDCard;
		
		private string _Flag;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _QQ;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPIDChanging(string value);
    partial void OnPIDChanged();
    partial void OnIDNoChanging(string value);
    partial void OnIDNoChanged();
    partial void OnDepNOChanging(string value);
    partial void OnDepNOChanged();
    partial void OnDepSectionNOChanging(string value);
    partial void OnDepSectionNOChanged();
    partial void OnSexNoChanging(string value);
    partial void OnSexNoChanged();
    partial void OnCardNoChanging(long value);
    partial void OnCardNoChanged();
    partial void OnAccountNoChanging(long value);
    partial void OnAccountNoChanged();
    partial void OnIDCardChanging(string value);
    partial void OnIDCardChanged();
    partial void OnFlagChanging(string value);
    partial void OnFlagChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnQQChanging(string value);
    partial void OnQQChanged();
    #endregion
		
		public T_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(31) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNo", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string IDNo
		{
			get
			{
				return this._IDNo;
			}
			set
			{
				if ((this._IDNo != value))
				{
					this.OnIDNoChanging(value);
					this.SendPropertyChanging();
					this._IDNo = value;
					this.SendPropertyChanged("IDNo");
					this.OnIDNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNO", DbType="NVarChar(21) NOT NULL", CanBeNull=false)]
		public string DepNO
		{
			get
			{
				return this._DepNO;
			}
			set
			{
				if ((this._DepNO != value))
				{
					this.OnDepNOChanging(value);
					this.SendPropertyChanging();
					this._DepNO = value;
					this.SendPropertyChanged("DepNO");
					this.OnDepNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepSectionNO", DbType="NVarChar(21)")]
		public string DepSectionNO
		{
			get
			{
				return this._DepSectionNO;
			}
			set
			{
				if ((this._DepSectionNO != value))
				{
					this.OnDepSectionNOChanging(value);
					this.SendPropertyChanging();
					this._DepSectionNO = value;
					this.SendPropertyChanged("DepSectionNO");
					this.OnDepSectionNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexNo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SexNo
		{
			get
			{
				return this._SexNo;
			}
			set
			{
				if ((this._SexNo != value))
				{
					this.OnSexNoChanging(value);
					this.SendPropertyChanging();
					this._SexNo = value;
					this.SendPropertyChanged("SexNo");
					this.OnSexNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="BigInt NOT NULL")]
		public long CardNo
		{
			get
			{
				return this._CardNo;
			}
			set
			{
				if ((this._CardNo != value))
				{
					this.OnCardNoChanging(value);
					this.SendPropertyChanging();
					this._CardNo = value;
					this.SendPropertyChanged("CardNo");
					this.OnCardNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo", DbType="BigInt NOT NULL")]
		public long AccountNo
		{
			get
			{
				return this._AccountNo;
			}
			set
			{
				if ((this._AccountNo != value))
				{
					this.OnAccountNoChanging(value);
					this.SendPropertyChanging();
					this._AccountNo = value;
					this.SendPropertyChanged("AccountNo");
					this.OnAccountNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCard", DbType="NVarChar(21) NOT NULL", CanBeNull=false)]
		public string IDCard
		{
			get
			{
				return this._IDCard;
			}
			set
			{
				if ((this._IDCard != value))
				{
					this.OnIDCardChanging(value);
					this.SendPropertyChanging();
					this._IDCard = value;
					this.SendPropertyChanged("IDCard");
					this.OnIDCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(20)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QQ", DbType="NVarChar(20)")]
		public string QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this.OnQQChanging(value);
					this.SendPropertyChanging();
					this._QQ = value;
					this.SendPropertyChanged("QQ");
					this.OnQQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Department")]
	public partial class T_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DepNO;
		
		private int _SuitPeople;
		
		private string _DepName;
		
		private string _DepNickName;
		
		private int _DepTypeID;
		
		private string _DepType;
		
		private string _DepNotes;
		
		private bool _IsDelete;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDepNOChanging(string value);
    partial void OnDepNOChanged();
    partial void OnSuitPeopleChanging(int value);
    partial void OnSuitPeopleChanged();
    partial void OnDepNameChanging(string value);
    partial void OnDepNameChanged();
    partial void OnDepNickNameChanging(string value);
    partial void OnDepNickNameChanged();
    partial void OnDepTypeIDChanging(int value);
    partial void OnDepTypeIDChanged();
    partial void OnDepTypeChanging(string value);
    partial void OnDepTypeChanged();
    partial void OnDepNotesChanging(string value);
    partial void OnDepNotesChanged();
    partial void OnIsDeleteChanging(bool value);
    partial void OnIsDeleteChanged();
    #endregion
		
		public T_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNO", DbType="NVarChar(21) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DepNO
		{
			get
			{
				return this._DepNO;
			}
			set
			{
				if ((this._DepNO != value))
				{
					this.OnDepNOChanging(value);
					this.SendPropertyChanging();
					this._DepNO = value;
					this.SendPropertyChanged("DepNO");
					this.OnDepNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuitPeople", DbType="Int NOT NULL")]
		public int SuitPeople
		{
			get
			{
				return this._SuitPeople;
			}
			set
			{
				if ((this._SuitPeople != value))
				{
					this.OnSuitPeopleChanging(value);
					this.SendPropertyChanging();
					this._SuitPeople = value;
					this.SendPropertyChanged("SuitPeople");
					this.OnSuitPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NVarChar(41) NOT NULL", CanBeNull=false)]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this.OnDepNameChanging(value);
					this.SendPropertyChanging();
					this._DepName = value;
					this.SendPropertyChanged("DepName");
					this.OnDepNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNickName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DepNickName
		{
			get
			{
				return this._DepNickName;
			}
			set
			{
				if ((this._DepNickName != value))
				{
					this.OnDepNickNameChanging(value);
					this.SendPropertyChanging();
					this._DepNickName = value;
					this.SendPropertyChanged("DepNickName");
					this.OnDepNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepTypeID", DbType="Int NOT NULL")]
		public int DepTypeID
		{
			get
			{
				return this._DepTypeID;
			}
			set
			{
				if ((this._DepTypeID != value))
				{
					this.OnDepTypeIDChanging(value);
					this.SendPropertyChanging();
					this._DepTypeID = value;
					this.SendPropertyChanged("DepTypeID");
					this.OnDepTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DepType
		{
			get
			{
				return this._DepType;
			}
			set
			{
				if ((this._DepType != value))
				{
					this.OnDepTypeChanging(value);
					this.SendPropertyChanging();
					this._DepType = value;
					this.SendPropertyChanged("DepType");
					this.OnDepTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNotes", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DepNotes
		{
			get
			{
				return this._DepNotes;
			}
			set
			{
				if ((this._DepNotes != value))
				{
					this.OnDepNotesChanging(value);
					this.SendPropertyChanging();
					this._DepNotes = value;
					this.SendPropertyChanged("DepNotes");
					this.OnDepNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this.OnIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsDelete = value;
					this.SendPropertyChanged("IsDelete");
					this.OnIsDeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
