<?xml version="1.0" encoding="utf-8"?><Database Name="COMPUB" Class="WidgetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=E:\综合发布平台\Compublish\Compublish\ComPublishWeb\App_Data\COMPUB.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="WidgetDateLibrary.Properties.Settings" SettingsPropertyName="COMPUBConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ApplicationUnitsCss" Member="ApplicationUnitsCss">
    <Type Name="ApplicationUnitsCss">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="unitsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="css" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="res1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="res2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationUnitsShowStyle" Member="ApplicationUnitsShowStyle">
    <Type Name="ApplicationUnitsShowStyle">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebPageSet" Member="WebPageSet">
    <Type Name="WebPageSet">
      <Column Name="pageno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pagename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pageshowscape" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="descripte" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="iffrist" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="layoutstyle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Application" Member="Application">
    <Type Name="Application">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="appname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="note" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logourl" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="publishto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ispublish" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="operator" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastmodifytime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tags" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="passed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IfLoginShow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationDatasource" Member="ApplicationDatasource">
    <Type Name="ApplicationDatasource">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="applicationid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dsname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="unitsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dsurl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dsparams" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dataitems" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="isefficetive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="modifydate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="operator" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ifneedauthrity" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationPage" Member="ApplicationPage">
    <Type Name="ApplicationPage">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="showtypeid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="actionname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="appid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pagename" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="actionunits" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isStart" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isEffictive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lastmodifytime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="res1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="res2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationShowType" Member="ApplicationShowType">
    <Type Name="ApplicationShowType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FillMark" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FillCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="remark" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="viewdate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="res1" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="res2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationUnits" Member="ApplicationUnits">
    <Type Name="ApplicationUnits">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="applicationid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unitname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="datasourceid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="utype" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="containUnits" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ucontent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="showstyleid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="iseffictive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lastmodifytime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NextUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NextUnitShowType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="unitparams" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AuthErrorAlertUnit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="res2" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebPageUnits" Member="WebPageUnits">
    <Type Name="WebPageUnits">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pageid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pageunitid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ifloginshow" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="showcontainer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="widgettype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="showtitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="showorder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="specialCssFile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>