#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidgetDateLibrary.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="COMPUB.MDF")]
	public partial class WidgetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertApplicationDatasource(ApplicationDatasource instance);
    partial void UpdateApplicationDatasource(ApplicationDatasource instance);
    partial void DeleteApplicationDatasource(ApplicationDatasource instance);
    partial void InsertApplicationPage(ApplicationPage instance);
    partial void UpdateApplicationPage(ApplicationPage instance);
    partial void DeleteApplicationPage(ApplicationPage instance);
    partial void InsertApplicationShowType(ApplicationShowType instance);
    partial void UpdateApplicationShowType(ApplicationShowType instance);
    partial void DeleteApplicationShowType(ApplicationShowType instance);
    partial void InsertApplicationUnitsCss(ApplicationUnitsCss instance);
    partial void UpdateApplicationUnitsCss(ApplicationUnitsCss instance);
    partial void DeleteApplicationUnitsCss(ApplicationUnitsCss instance);
    partial void InsertApplicationUnitsShowStyle(ApplicationUnitsShowStyle instance);
    partial void UpdateApplicationUnitsShowStyle(ApplicationUnitsShowStyle instance);
    partial void DeleteApplicationUnitsShowStyle(ApplicationUnitsShowStyle instance);
    partial void InsertApplication(Application instance);
    partial void UpdateApplication(Application instance);
    partial void DeleteApplication(Application instance);
    partial void InsertApplicationUnits(ApplicationUnits instance);
    partial void UpdateApplicationUnits(ApplicationUnits instance);
    partial void DeleteApplicationUnits(ApplicationUnits instance);
    #endregion
		
		public WidgetDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["COMPUBConnectionString"].ConnectionString, mappingSource)
       {
			OnCreated();
		}
		
		public WidgetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WidgetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WidgetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WidgetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ApplicationDatasource> ApplicationDatasource
		{
			get
			{
				return this.GetTable<ApplicationDatasource>();
			}
		}
		
		public System.Data.Linq.Table<ApplicationPage> ApplicationPage
		{
			get
			{
				return this.GetTable<ApplicationPage>();
			}
		}
		
		public System.Data.Linq.Table<ApplicationShowType> ApplicationShowType
		{
			get
			{
				return this.GetTable<ApplicationShowType>();
			}
		}
		
		public System.Data.Linq.Table<ApplicationUnitsCss> ApplicationUnitsCss
		{
			get
			{
				return this.GetTable<ApplicationUnitsCss>();
			}
		}
		
		public System.Data.Linq.Table<ApplicationUnitsShowStyle> ApplicationUnitsShowStyle
		{
			get
			{
				return this.GetTable<ApplicationUnitsShowStyle>();
			}
		}
		
		public System.Data.Linq.Table<Application> Application
		{
			get
			{
				return this.GetTable<Application>();
			}
		}
		
		public System.Data.Linq.Table<ApplicationUnits> ApplicationUnits
		{
			get
			{
				return this.GetTable<ApplicationUnits>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApplicationDatasource")]
	public partial class ApplicationDatasource : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _dsname;
		
		private System.Nullable<int> _unitsid;
		
		private string _dsurl;
		
		private string _dsparams;
		
		private string _dataitems;
		
		private System.Nullable<bool> _isefficetive;
		
		private System.Nullable<System.DateTime> _modifydate;
		
		private string _operator;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndsnameChanging(string value);
    partial void OndsnameChanged();
    partial void OnunitsidChanging(System.Nullable<int> value);
    partial void OnunitsidChanged();
    partial void OndsurlChanging(string value);
    partial void OndsurlChanged();
    partial void OndsparamsChanging(string value);
    partial void OndsparamsChanged();
    partial void OndataitemsChanging(string value);
    partial void OndataitemsChanged();
    partial void OnisefficetiveChanging(System.Nullable<bool> value);
    partial void OnisefficetiveChanged();
    partial void OnmodifydateChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifydateChanged();
    partial void OnoperatorChanging(string value);
    partial void OnoperatorChanged();
    #endregion
		
		public ApplicationDatasource()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string dsname
		{
			get
			{
				return this._dsname;
			}
			set
			{
				if ((this._dsname != value))
				{
					this.OndsnameChanging(value);
					this.SendPropertyChanging();
					this._dsname = value;
					this.SendPropertyChanged("dsname");
					this.OndsnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitsid", DbType="Int")]
		public System.Nullable<int> unitsid
		{
			get
			{
				return this._unitsid;
			}
			set
			{
				if ((this._unitsid != value))
				{
					this.OnunitsidChanging(value);
					this.SendPropertyChanging();
					this._unitsid = value;
					this.SendPropertyChanged("unitsid");
					this.OnunitsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsurl", DbType="NVarChar(255)")]
		public string dsurl
		{
			get
			{
				return this._dsurl;
			}
			set
			{
				if ((this._dsurl != value))
				{
					this.OndsurlChanging(value);
					this.SendPropertyChanging();
					this._dsurl = value;
					this.SendPropertyChanged("dsurl");
					this.OndsurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsparams", DbType="NVarChar(255)")]
		public string dsparams
		{
			get
			{
				return this._dsparams;
			}
			set
			{
				if ((this._dsparams != value))
				{
					this.OndsparamsChanging(value);
					this.SendPropertyChanging();
					this._dsparams = value;
					this.SendPropertyChanged("dsparams");
					this.OndsparamsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataitems", DbType="NVarChar(255)")]
		public string dataitems
		{
			get
			{
				return this._dataitems;
			}
			set
			{
				if ((this._dataitems != value))
				{
					this.OndataitemsChanging(value);
					this.SendPropertyChanging();
					this._dataitems = value;
					this.SendPropertyChanged("dataitems");
					this.OndataitemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isefficetive", DbType="Bit")]
		public System.Nullable<bool> isefficetive
		{
			get
			{
				return this._isefficetive;
			}
			set
			{
				if ((this._isefficetive != value))
				{
					this.OnisefficetiveChanging(value);
					this.SendPropertyChanging();
					this._isefficetive = value;
					this.SendPropertyChanged("isefficetive");
					this.OnisefficetiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modifydate", DbType="DateTime")]
		public System.Nullable<System.DateTime> modifydate
		{
			get
			{
				return this._modifydate;
			}
			set
			{
				if ((this._modifydate != value))
				{
					this.OnmodifydateChanging(value);
					this.SendPropertyChanging();
					this._modifydate = value;
					this.SendPropertyChanged("modifydate");
					this.OnmodifydateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operator", Storage="_operator", DbType="NVarChar(10)")]
		public string @operator
		{
			get
			{
				return this._operator;
			}
			set
			{
				if ((this._operator != value))
				{
					this.OnoperatorChanging(value);
					this.SendPropertyChanging();
					this._operator = value;
					this.SendPropertyChanged("@operator");
					this.OnoperatorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApplicationPage")]
	public partial class ApplicationPage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _showtypeid;
		
		private string _actionname;
		
		private string _note;
		
		private System.Nullable<int> _appid;
		
		private string _pagename;
		
		private string _actionunits;
		
		private System.Nullable<bool> _isStart;
		
		private System.Nullable<bool> _isEffictive;
		
		private System.Nullable<System.DateTime> _lastmodifytime;
		
		private string _res1;
		
		private string _res2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnshowtypeidChanging(System.Nullable<int> value);
    partial void OnshowtypeidChanged();
    partial void OnactionnameChanging(string value);
    partial void OnactionnameChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OnappidChanging(System.Nullable<int> value);
    partial void OnappidChanged();
    partial void OnpagenameChanging(string value);
    partial void OnpagenameChanged();
    partial void OnactionunitsChanging(string value);
    partial void OnactionunitsChanged();
    partial void OnisStartChanging(System.Nullable<bool> value);
    partial void OnisStartChanged();
    partial void OnisEffictiveChanging(System.Nullable<bool> value);
    partial void OnisEffictiveChanged();
    partial void OnlastmodifytimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifytimeChanged();
    partial void Onres1Changing(string value);
    partial void Onres1Changed();
    partial void Onres2Changing(string value);
    partial void Onres2Changed();
    #endregion
		
		public ApplicationPage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showtypeid", DbType="Int")]
		public System.Nullable<int> showtypeid
		{
			get
			{
				return this._showtypeid;
			}
			set
			{
				if ((this._showtypeid != value))
				{
					this.OnshowtypeidChanging(value);
					this.SendPropertyChanging();
					this._showtypeid = value;
					this.SendPropertyChanged("showtypeid");
					this.OnshowtypeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actionname", DbType="NVarChar(20)")]
		public string actionname
		{
			get
			{
				return this._actionname;
			}
			set
			{
				if ((this._actionname != value))
				{
					this.OnactionnameChanging(value);
					this.SendPropertyChanging();
					this._actionname = value;
					this.SendPropertyChanged("actionname");
					this.OnactionnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(50)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appid", DbType="Int")]
		public System.Nullable<int> appid
		{
			get
			{
				return this._appid;
			}
			set
			{
				if ((this._appid != value))
				{
					this.OnappidChanging(value);
					this.SendPropertyChanging();
					this._appid = value;
					this.SendPropertyChanged("appid");
					this.OnappidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagename", DbType="NVarChar(50)")]
		public string pagename
		{
			get
			{
				return this._pagename;
			}
			set
			{
				if ((this._pagename != value))
				{
					this.OnpagenameChanging(value);
					this.SendPropertyChanging();
					this._pagename = value;
					this.SendPropertyChanged("pagename");
					this.OnpagenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actionunits", DbType="NVarChar(50)")]
		public string actionunits
		{
			get
			{
				return this._actionunits;
			}
			set
			{
				if ((this._actionunits != value))
				{
					this.OnactionunitsChanging(value);
					this.SendPropertyChanging();
					this._actionunits = value;
					this.SendPropertyChanged("actionunits");
					this.OnactionunitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isStart", DbType="Bit")]
		public System.Nullable<bool> isStart
		{
			get
			{
				return this._isStart;
			}
			set
			{
				if ((this._isStart != value))
				{
					this.OnisStartChanging(value);
					this.SendPropertyChanging();
					this._isStart = value;
					this.SendPropertyChanged("isStart");
					this.OnisStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isEffictive", DbType="Bit")]
		public System.Nullable<bool> isEffictive
		{
			get
			{
				return this._isEffictive;
			}
			set
			{
				if ((this._isEffictive != value))
				{
					this.OnisEffictiveChanging(value);
					this.SendPropertyChanging();
					this._isEffictive = value;
					this.SendPropertyChanged("isEffictive");
					this.OnisEffictiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifytime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastmodifytime
		{
			get
			{
				return this._lastmodifytime;
			}
			set
			{
				if ((this._lastmodifytime != value))
				{
					this.OnlastmodifytimeChanging(value);
					this.SendPropertyChanging();
					this._lastmodifytime = value;
					this.SendPropertyChanged("lastmodifytime");
					this.OnlastmodifytimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res1", DbType="NChar(10)")]
		public string res1
		{
			get
			{
				return this._res1;
			}
			set
			{
				if ((this._res1 != value))
				{
					this.Onres1Changing(value);
					this.SendPropertyChanging();
					this._res1 = value;
					this.SendPropertyChanged("res1");
					this.Onres1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res2", DbType="NChar(10)")]
		public string res2
		{
			get
			{
				return this._res2;
			}
			set
			{
				if ((this._res2 != value))
				{
					this.Onres2Changing(value);
					this.SendPropertyChanging();
					this._res2 = value;
					this.SendPropertyChanged("res2");
					this.Onres2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApplicationShowType")]
	public partial class ApplicationShowType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _FillMark;
		
		private int _FillCount;
		
		private string _remark;
		
		private string _viewdate;
		
		private string _res1;
		
		private string _res2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnFillMarkChanging(string value);
    partial void OnFillMarkChanged();
    partial void OnFillCountChanging(int value);
    partial void OnFillCountChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OnviewdateChanging(string value);
    partial void OnviewdateChanged();
    partial void Onres1Changing(string value);
    partial void Onres1Changed();
    partial void Onres2Changing(string value);
    partial void Onres2Changed();
    #endregion
		
		public ApplicationShowType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FillMark", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FillMark
		{
			get
			{
				return this._FillMark;
			}
			set
			{
				if ((this._FillMark != value))
				{
					this.OnFillMarkChanging(value);
					this.SendPropertyChanging();
					this._FillMark = value;
					this.SendPropertyChanged("FillMark");
					this.OnFillMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FillCount", DbType="Int NOT NULL")]
		public int FillCount
		{
			get
			{
				return this._FillCount;
			}
			set
			{
				if ((this._FillCount != value))
				{
					this.OnFillCountChanging(value);
					this.SendPropertyChanging();
					this._FillCount = value;
					this.SendPropertyChanged("FillCount");
					this.OnFillCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark", DbType="NVarChar(MAX)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viewdate", DbType="NVarChar(MAX)")]
		public string viewdate
		{
			get
			{
				return this._viewdate;
			}
			set
			{
				if ((this._viewdate != value))
				{
					this.OnviewdateChanging(value);
					this.SendPropertyChanging();
					this._viewdate = value;
					this.SendPropertyChanged("viewdate");
					this.OnviewdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res1", DbType="NChar(10)")]
		public string res1
		{
			get
			{
				return this._res1;
			}
			set
			{
				if ((this._res1 != value))
				{
					this.Onres1Changing(value);
					this.SendPropertyChanging();
					this._res1 = value;
					this.SendPropertyChanged("res1");
					this.Onres1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res2", DbType="NChar(10)")]
		public string res2
		{
			get
			{
				return this._res2;
			}
			set
			{
				if ((this._res2 != value))
				{
					this.Onres2Changing(value);
					this.SendPropertyChanging();
					this._res2 = value;
					this.SendPropertyChanged("res2");
					this.Onres2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApplicationUnitsCss")]
	public partial class ApplicationUnitsCss : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _unitsid;
		
		private string _name;
		
		private string _css;
		
		private string _res1;
		
		private string _res2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnunitsidChanging(System.Nullable<int> value);
    partial void OnunitsidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncssChanging(string value);
    partial void OncssChanged();
    partial void Onres1Changing(string value);
    partial void Onres1Changed();
    partial void Onres2Changing(string value);
    partial void Onres2Changed();
    #endregion
		
		public ApplicationUnitsCss()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitsid", DbType="Int")]
		public System.Nullable<int> unitsid
		{
			get
			{
				return this._unitsid;
			}
			set
			{
				if ((this._unitsid != value))
				{
					this.OnunitsidChanging(value);
					this.SendPropertyChanging();
					this._unitsid = value;
					this.SendPropertyChanged("unitsid");
					this.OnunitsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_css", DbType="NVarChar(20)")]
		public string css
		{
			get
			{
				return this._css;
			}
			set
			{
				if ((this._css != value))
				{
					this.OncssChanging(value);
					this.SendPropertyChanging();
					this._css = value;
					this.SendPropertyChanged("css");
					this.OncssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res1", DbType="NChar(10)")]
		public string res1
		{
			get
			{
				return this._res1;
			}
			set
			{
				if ((this._res1 != value))
				{
					this.Onres1Changing(value);
					this.SendPropertyChanging();
					this._res1 = value;
					this.SendPropertyChanged("res1");
					this.Onres1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res2", DbType="NChar(10)")]
		public string res2
		{
			get
			{
				return this._res2;
			}
			set
			{
				if ((this._res2 != value))
				{
					this.Onres2Changing(value);
					this.SendPropertyChanging();
					this._res2 = value;
					this.SendPropertyChanged("res2");
					this.Onres2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApplicationUnitsShowStyle")]
	public partial class ApplicationUnitsShowStyle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _note;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
		
		public ApplicationUnitsShowStyle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(50)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Application")]
	public partial class Application : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _appname;
		
		private string _note;
		
		private System.Nullable<int> _priority;
		
		private string _logourl;
		
		private string _publishto;
		
		private System.Nullable<bool> _ispublish;
		
		private string _operator;
		
		private System.Nullable<System.DateTime> _lastmodifytime;
		
		private string _tags;
		
		private System.Nullable<int> _passed;
		
		private System.Nullable<int> _ShowType;
		
		private System.Nullable<bool> _IfLoginShow;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnappnameChanging(string value);
    partial void OnappnameChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    partial void OnlogourlChanging(string value);
    partial void OnlogourlChanged();
    partial void OnpublishtoChanging(string value);
    partial void OnpublishtoChanged();
    partial void OnispublishChanging(System.Nullable<bool> value);
    partial void OnispublishChanged();
    partial void OnoperatorChanging(string value);
    partial void OnoperatorChanged();
    partial void OnlastmodifytimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifytimeChanged();
    partial void OntagsChanging(string value);
    partial void OntagsChanged();
    partial void OnpassedChanging(System.Nullable<int> value);
    partial void OnpassedChanged();
    partial void OnShowTypeChanging(System.Nullable<int> value);
    partial void OnShowTypeChanged();
    partial void OnIfLoginShowChanging(System.Nullable<bool> value);
    partial void OnIfLoginShowChanged();
    #endregion
		
		public Application()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string appname
		{
			get
			{
				return this._appname;
			}
			set
			{
				if ((this._appname != value))
				{
					this.OnappnameChanging(value);
					this.SendPropertyChanging();
					this._appname = value;
					this.SendPropertyChanged("appname");
					this.OnappnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(MAX)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int")]
		public System.Nullable<int> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logourl", DbType="NVarChar(50)")]
		public string logourl
		{
			get
			{
				return this._logourl;
			}
			set
			{
				if ((this._logourl != value))
				{
					this.OnlogourlChanging(value);
					this.SendPropertyChanging();
					this._logourl = value;
					this.SendPropertyChanged("logourl");
					this.OnlogourlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishto", DbType="NVarChar(50)")]
		public string publishto
		{
			get
			{
				return this._publishto;
			}
			set
			{
				if ((this._publishto != value))
				{
					this.OnpublishtoChanging(value);
					this.SendPropertyChanging();
					this._publishto = value;
					this.SendPropertyChanged("publishto");
					this.OnpublishtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ispublish", DbType="Bit")]
		public System.Nullable<bool> ispublish
		{
			get
			{
				return this._ispublish;
			}
			set
			{
				if ((this._ispublish != value))
				{
					this.OnispublishChanging(value);
					this.SendPropertyChanging();
					this._ispublish = value;
					this.SendPropertyChanged("ispublish");
					this.OnispublishChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="operator", Storage="_operator", DbType="NVarChar(50)")]
		public string @operator
		{
			get
			{
				return this._operator;
			}
			set
			{
				if ((this._operator != value))
				{
					this.OnoperatorChanging(value);
					this.SendPropertyChanging();
					this._operator = value;
					this.SendPropertyChanged("@operator");
					this.OnoperatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifytime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastmodifytime
		{
			get
			{
				return this._lastmodifytime;
			}
			set
			{
				if ((this._lastmodifytime != value))
				{
					this.OnlastmodifytimeChanging(value);
					this.SendPropertyChanging();
					this._lastmodifytime = value;
					this.SendPropertyChanged("lastmodifytime");
					this.OnlastmodifytimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tags", DbType="NVarChar(MAX)")]
		public string tags
		{
			get
			{
				return this._tags;
			}
			set
			{
				if ((this._tags != value))
				{
					this.OntagsChanging(value);
					this.SendPropertyChanging();
					this._tags = value;
					this.SendPropertyChanged("tags");
					this.OntagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passed", DbType="Int")]
		public System.Nullable<int> passed
		{
			get
			{
				return this._passed;
			}
			set
			{
				if ((this._passed != value))
				{
					this.OnpassedChanging(value);
					this.SendPropertyChanging();
					this._passed = value;
					this.SendPropertyChanged("passed");
					this.OnpassedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowType", DbType="Int")]
		public System.Nullable<int> ShowType
		{
			get
			{
				return this._ShowType;
			}
			set
			{
				if ((this._ShowType != value))
				{
					this.OnShowTypeChanging(value);
					this.SendPropertyChanging();
					this._ShowType = value;
					this.SendPropertyChanged("ShowType");
					this.OnShowTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IfLoginShow", DbType="Bit")]
		public System.Nullable<bool> IfLoginShow
		{
			get
			{
				return this._IfLoginShow;
			}
			set
			{
				if ((this._IfLoginShow != value))
				{
					this.OnIfLoginShowChanging(value);
					this.SendPropertyChanging();
					this._IfLoginShow = value;
					this.SendPropertyChanged("IfLoginShow");
					this.OnIfLoginShowChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApplicationUnits")]
	public partial class ApplicationUnits : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _unitname;
		
		private System.Nullable<int> _datasourceid;
		
		private System.Nullable<int> _utype;
		
		private string _ucontent;
		
		private System.Nullable<int> _showstyleid;
		
		private System.Nullable<bool> _iseffictive;
		
		private System.Nullable<System.DateTime> _lastmodifytime;
		
		private System.Nullable<int> _NextPage;
		
		private string _NextPageShowType;
		
		private string _params;
		
		private string _res2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnunitnameChanging(string value);
    partial void OnunitnameChanged();
    partial void OndatasourceidChanging(System.Nullable<int> value);
    partial void OndatasourceidChanged();
    partial void OnutypeChanging(System.Nullable<int> value);
    partial void OnutypeChanged();
    partial void OnucontentChanging(string value);
    partial void OnucontentChanged();
    partial void OnshowstyleidChanging(System.Nullable<int> value);
    partial void OnshowstyleidChanged();
    partial void OniseffictiveChanging(System.Nullable<bool> value);
    partial void OniseffictiveChanged();
    partial void OnlastmodifytimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifytimeChanged();
    partial void OnNextPageChanging(System.Nullable<int> value);
    partial void OnNextPageChanged();
    partial void OnNextPageShowTypeChanging(string value);
    partial void OnNextPageShowTypeChanged();
    partial void OntheparamsChanging(string value);
    partial void OntheparamsChanged();
    partial void Onres2Changing(string value);
    partial void Onres2Changed();
    #endregion
		
		public ApplicationUnits()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this.OnunitnameChanging(value);
					this.SendPropertyChanging();
					this._unitname = value;
					this.SendPropertyChanged("unitname");
					this.OnunitnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datasourceid", DbType="Int")]
		public System.Nullable<int> datasourceid
		{
			get
			{
				return this._datasourceid;
			}
			set
			{
				if ((this._datasourceid != value))
				{
					this.OndatasourceidChanging(value);
					this.SendPropertyChanging();
					this._datasourceid = value;
					this.SendPropertyChanged("datasourceid");
					this.OndatasourceidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_utype", DbType="Int")]
		public System.Nullable<int> utype
		{
			get
			{
				return this._utype;
			}
			set
			{
				if ((this._utype != value))
				{
					this.OnutypeChanging(value);
					this.SendPropertyChanging();
					this._utype = value;
					this.SendPropertyChanged("utype");
					this.OnutypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucontent", DbType="NVarChar(MAX)")]
		public string ucontent
		{
			get
			{
				return this._ucontent;
			}
			set
			{
				if ((this._ucontent != value))
				{
					this.OnucontentChanging(value);
					this.SendPropertyChanging();
					this._ucontent = value;
					this.SendPropertyChanged("ucontent");
					this.OnucontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showstyleid", DbType="Int")]
		public System.Nullable<int> showstyleid
		{
			get
			{
				return this._showstyleid;
			}
			set
			{
				if ((this._showstyleid != value))
				{
					this.OnshowstyleidChanging(value);
					this.SendPropertyChanging();
					this._showstyleid = value;
					this.SendPropertyChanged("showstyleid");
					this.OnshowstyleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iseffictive", DbType="Bit")]
		public System.Nullable<bool> iseffictive
		{
			get
			{
				return this._iseffictive;
			}
			set
			{
				if ((this._iseffictive != value))
				{
					this.OniseffictiveChanging(value);
					this.SendPropertyChanging();
					this._iseffictive = value;
					this.SendPropertyChanged("iseffictive");
					this.OniseffictiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifytime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastmodifytime
		{
			get
			{
				return this._lastmodifytime;
			}
			set
			{
				if ((this._lastmodifytime != value))
				{
					this.OnlastmodifytimeChanging(value);
					this.SendPropertyChanging();
					this._lastmodifytime = value;
					this.SendPropertyChanged("lastmodifytime");
					this.OnlastmodifytimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextPage", DbType="Int")]
		public System.Nullable<int> NextPage
		{
			get
			{
				return this._NextPage;
			}
			set
			{
				if ((this._NextPage != value))
				{
					this.OnNextPageChanging(value);
					this.SendPropertyChanging();
					this._NextPage = value;
					this.SendPropertyChanged("NextPage");
					this.OnNextPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextPageShowType", DbType="NVarChar(20)")]
		public string NextPageShowType
		{
			get
			{
				return this._NextPageShowType;
			}
			set
			{
				if ((this._NextPageShowType != value))
				{
					this.OnNextPageShowTypeChanging(value);
					this.SendPropertyChanging();
					this._NextPageShowType = value;
					this.SendPropertyChanged("NextPageShowType");
					this.OnNextPageShowTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="params", Storage="_params", DbType="NVarChar(100)")]
		public string theparams
		{
			get
			{
				return this._params;
			}
			set
			{
				if ((this._params != value))
				{
					this.OntheparamsChanging(value);
					this.SendPropertyChanging();
					this._params = value;
					this.SendPropertyChanged("theparams");
					this.OntheparamsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res2", DbType="NChar(10)")]
		public string res2
		{
			get
			{
				return this._res2;
			}
			set
			{
				if ((this._res2 != value))
				{
					this.Onres2Changing(value);
					this.SendPropertyChanging();
					this._res2 = value;
					this.SendPropertyChanged("res2");
					this.Onres2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
