//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidgetDateLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\综合发布平台\\ComPublishWeb\\ComPublishWeb\\C" +
            "omPublishWeb\\App_Data\\COMPUB.mdf;Integrated Security=True;Connect Timeout=30;Use" +
            "r Instance=True")]
        public string COMPUBConnectionString1 {
            get {
                return ((string)(this["COMPUBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\综合发布平台\\ComPublishWeb_Widget\\ComPubli" +
            "shWeb_Widget\\ComPublishWeb\\App_Data\\COMPUB.mdf;Integrated Security=True;User Ins" +
            "tance=True")]
        public string COMPUBConnectionString {
            get {
                return ((string)(this["COMPUBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\综合发布平台\\ComPublishWeb\\ComPublishWeb_W" +
            "idget\\ComPublishWeb\\App_Data\\COMPUB.mdf;Integrated Security=True;User Instance=T" +
            "rue")]
        public string COMPUBConnectionString2 {
            get {
                return ((string)(this["COMPUBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=210.42.159.78;Initial Catalog=COMPUB.MDF;Persist Security Info=True;U" +
            "ser ID=developer")]
        public string COMPUB_MDFConnectionString {
            get {
                return ((string)(this["COMPUB_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\综合发布平台\\Compublish\\Compublish\\ComPubl" +
            "ishWeb\\App_Data\\COMPUB.mdf;Integrated Security=True;Connect Timeout=30;User Inst" +
            "ance=True")]
        public string COMPUBConnectionString3 {
            get {
                return ((string)(this["COMPUBConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\综合发布平台\\Compublish\\Compublish\\ComPubl" +
            "ishWeb\\App_Data\\COMPUB.mdf;Integrated Security=True;Connect Timeout=30;User Inst" +
            "ance=True")]
        public string COMPUBConnectionString4 {
            get {
                return ((string)(this["COMPUBConnectionString4"]));
            }
        }
    }
}
