#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthMSModelsLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WHSMPERSAUTH")]
	public partial class AuthMSLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertT_UserRole(T_UserRole instance);
    partial void UpdateT_UserRole(T_UserRole instance);
    partial void DeleteT_UserRole(T_UserRole instance);
    partial void InsertT_User(T_User instance);
    partial void UpdateT_User(T_User instance);
    partial void DeleteT_User(T_User instance);
    partial void InsertT_RoleModule(T_RoleModule instance);
    partial void UpdateT_RoleModule(T_RoleModule instance);
    partial void DeleteT_RoleModule(T_RoleModule instance);
    partial void InsertT_Role(T_Role instance);
    partial void UpdateT_Role(T_Role instance);
    partial void DeleteT_Role(T_Role instance);
    partial void InsertT_Module(T_Module instance);
    partial void UpdateT_Module(T_Module instance);
    partial void DeleteT_Module(T_Module instance);
    partial void InsertT_Department(T_Department instance);
    partial void UpdateT_Department(T_Department instance);
    partial void DeleteT_Department(T_Department instance);
    partial void InsertDIC_PID(DIC_PID instance);
    partial void UpdateDIC_PID(DIC_PID instance);
    partial void DeleteDIC_PID(DIC_PID instance);
    #endregion
		
		public AuthMSLinqDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WHSMPERSAUTHConnectionString"].ConnectionString, mappingSource)
    {
        OnCreated();
    }
		
		public AuthMSLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthMSLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthMSLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuthMSLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_UserRole> T_UserRole
		{
			get
			{
				return this.GetTable<T_UserRole>();
			}
		}
		
		public System.Data.Linq.Table<T_User> T_User
		{
			get
			{
				return this.GetTable<T_User>();
			}
		}
		
		public System.Data.Linq.Table<T_RoleModule> T_RoleModule
		{
			get
			{
				return this.GetTable<T_RoleModule>();
			}
		}
		
		public System.Data.Linq.Table<T_Role> T_Role
		{
			get
			{
				return this.GetTable<T_Role>();
			}
		}
		
		public System.Data.Linq.Table<T_Module> T_Module
		{
			get
			{
				return this.GetTable<T_Module>();
			}
		}
		
		public System.Data.Linq.Table<T_Department> T_Department
		{
			get
			{
				return this.GetTable<T_Department>();
			}
		}
		
		public System.Data.Linq.Table<DIC_PID> DIC_PID
		{
			get
			{
				return this.GetTable<DIC_PID>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_UserRole")]
	public partial class T_UserRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private int _RoleID;
		
		private int _OperatorID;
		
		private string _OperatorName;
		
		private System.DateTime _OperateDate;
		
		private int _ID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnOperatorIDChanging(int value);
    partial void OnOperatorIDChanged();
    partial void OnOperatorNameChanging(string value);
    partial void OnOperatorNameChanged();
    partial void OnOperateDateChanging(System.DateTime value);
    partial void OnOperateDateChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public T_UserRole()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorID", DbType="Int NOT NULL")]
		public int OperatorID
		{
			get
			{
				return this._OperatorID;
			}
			set
			{
				if ((this._OperatorID != value))
				{
					this.OnOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._OperatorID = value;
					this.SendPropertyChanged("OperatorID");
					this.OnOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OperatorName
		{
			get
			{
				return this._OperatorName;
			}
			set
			{
				if ((this._OperatorName != value))
				{
					this.OnOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._OperatorName = value;
					this.SendPropertyChanged("OperatorName");
					this.OnOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperateDate", DbType="Date NOT NULL")]
		public System.DateTime OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this.OnOperateDateChanging(value);
					this.SendPropertyChanging();
					this._OperateDate = value;
					this.SendPropertyChanged("OperateDate");
					this.OnOperateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_User")]
	public partial class T_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserID;
		
		private string _Password;
		
		private string _UserName;
		
		private string _PID;
		
		private string _IDNo;
		
		private string _DepNO;
		
		private string _DepSectionNO;
		
		private string _SexNo;
		
		private long _CardNo;
		
		private long _AccountNo;
		
		private string _IDCard;
		
		private string _Flag;
		
		private string _Telephone;
		
		private string _Email;
		
		private string _QQ;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPIDChanging(string value);
    partial void OnPIDChanged();
    partial void OnIDNoChanging(string value);
    partial void OnIDNoChanged();
    partial void OnDepNOChanging(string value);
    partial void OnDepNOChanged();
    partial void OnDepSectionNOChanging(string value);
    partial void OnDepSectionNOChanged();
    partial void OnSexNoChanging(string value);
    partial void OnSexNoChanged();
    partial void OnCardNoChanging(long value);
    partial void OnCardNoChanged();
    partial void OnAccountNoChanging(long value);
    partial void OnAccountNoChanged();
    partial void OnIDCardChanging(string value);
    partial void OnIDCardChanged();
    partial void OnFlagChanging(string value);
    partial void OnFlagChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnQQChanging(string value);
    partial void OnQQChanged();
    #endregion
		
		public T_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(31) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNo", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string IDNo
		{
			get
			{
				return this._IDNo;
			}
			set
			{
				if ((this._IDNo != value))
				{
					this.OnIDNoChanging(value);
					this.SendPropertyChanging();
					this._IDNo = value;
					this.SendPropertyChanged("IDNo");
					this.OnIDNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNO", DbType="NVarChar(21) NOT NULL", CanBeNull=false)]
		public string DepNO
		{
			get
			{
				return this._DepNO;
			}
			set
			{
				if ((this._DepNO != value))
				{
					this.OnDepNOChanging(value);
					this.SendPropertyChanging();
					this._DepNO = value;
					this.SendPropertyChanged("DepNO");
					this.OnDepNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepSectionNO", DbType="NVarChar(21)")]
		public string DepSectionNO
		{
			get
			{
				return this._DepSectionNO;
			}
			set
			{
				if ((this._DepSectionNO != value))
				{
					this.OnDepSectionNOChanging(value);
					this.SendPropertyChanging();
					this._DepSectionNO = value;
					this.SendPropertyChanged("DepSectionNO");
					this.OnDepSectionNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexNo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SexNo
		{
			get
			{
				return this._SexNo;
			}
			set
			{
				if ((this._SexNo != value))
				{
					this.OnSexNoChanging(value);
					this.SendPropertyChanging();
					this._SexNo = value;
					this.SendPropertyChanged("SexNo");
					this.OnSexNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="BigInt NOT NULL")]
		public long CardNo
		{
			get
			{
				return this._CardNo;
			}
			set
			{
				if ((this._CardNo != value))
				{
					this.OnCardNoChanging(value);
					this.SendPropertyChanging();
					this._CardNo = value;
					this.SendPropertyChanged("CardNo");
					this.OnCardNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo", DbType="BigInt NOT NULL")]
		public long AccountNo
		{
			get
			{
				return this._AccountNo;
			}
			set
			{
				if ((this._AccountNo != value))
				{
					this.OnAccountNoChanging(value);
					this.SendPropertyChanging();
					this._AccountNo = value;
					this.SendPropertyChanged("AccountNo");
					this.OnAccountNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCard", DbType="NVarChar(21) NOT NULL", CanBeNull=false)]
		public string IDCard
		{
			get
			{
				return this._IDCard;
			}
			set
			{
				if ((this._IDCard != value))
				{
					this.OnIDCardChanging(value);
					this.SendPropertyChanging();
					this._IDCard = value;
					this.SendPropertyChanged("IDCard");
					this.OnIDCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(20)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QQ", DbType="NVarChar(20)")]
		public string QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this.OnQQChanging(value);
					this.SendPropertyChanging();
					this._QQ = value;
					this.SendPropertyChanged("QQ");
					this.OnQQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_RoleModule")]
	public partial class T_RoleModule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleID;
		
		private int _RoleID;
		
		private string _RightType;
		
		private int _OperatorID;
		
		private string _OperatorName;
		
		private System.DateTime _OperateDate;
		
		private int _ID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIDChanging(int value);
    partial void OnModuleIDChanged();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRightTypeChanging(string value);
    partial void OnRightTypeChanged();
    partial void OnOperatorIDChanging(int value);
    partial void OnOperatorIDChanged();
    partial void OnOperatorNameChanging(string value);
    partial void OnOperatorNameChanged();
    partial void OnOperateDateChanging(System.DateTime value);
    partial void OnOperateDateChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public T_RoleModule()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="Int NOT NULL")]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RightType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string RightType
		{
			get
			{
				return this._RightType;
			}
			set
			{
				if ((this._RightType != value))
				{
					this.OnRightTypeChanging(value);
					this.SendPropertyChanging();
					this._RightType = value;
					this.SendPropertyChanged("RightType");
					this.OnRightTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorID", DbType="Int NOT NULL")]
		public int OperatorID
		{
			get
			{
				return this._OperatorID;
			}
			set
			{
				if ((this._OperatorID != value))
				{
					this.OnOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._OperatorID = value;
					this.SendPropertyChanged("OperatorID");
					this.OnOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OperatorName
		{
			get
			{
				return this._OperatorName;
			}
			set
			{
				if ((this._OperatorName != value))
				{
					this.OnOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._OperatorName = value;
					this.SendPropertyChanged("OperatorName");
					this.OnOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperateDate", DbType="Date NOT NULL")]
		public System.DateTime OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this.OnOperateDateChanging(value);
					this.SendPropertyChanging();
					this._OperateDate = value;
					this.SendPropertyChanged("OperateDate");
					this.OnOperateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Role")]
	public partial class T_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private int _RoleParentID;
		
		private string _RoleName;
		
		private string _RoleFunctionNotes;
		
		private bool _IsChildrenRole;
		
		private bool _IsDelete;
		
		private int _OperatorID;
		
		private string _OperatorName;
		
		private System.DateTime _OperateDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRoleParentIDChanging(int value);
    partial void OnRoleParentIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnRoleFunctionNotesChanging(string value);
    partial void OnRoleFunctionNotesChanged();
    partial void OnIsChildrenRoleChanging(bool value);
    partial void OnIsChildrenRoleChanged();
    partial void OnIsDeleteChanging(bool value);
    partial void OnIsDeleteChanged();
    partial void OnOperatorIDChanging(int value);
    partial void OnOperatorIDChanged();
    partial void OnOperatorNameChanging(string value);
    partial void OnOperatorNameChanged();
    partial void OnOperateDateChanging(System.DateTime value);
    partial void OnOperateDateChanged();
    #endregion
		
		public T_Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleParentID", DbType="Int NOT NULL")]
		public int RoleParentID
		{
			get
			{
				return this._RoleParentID;
			}
			set
			{
				if ((this._RoleParentID != value))
				{
					this.OnRoleParentIDChanging(value);
					this.SendPropertyChanging();
					this._RoleParentID = value;
					this.SendPropertyChanged("RoleParentID");
					this.OnRoleParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleFunctionNotes", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string RoleFunctionNotes
		{
			get
			{
				return this._RoleFunctionNotes;
			}
			set
			{
				if ((this._RoleFunctionNotes != value))
				{
					this.OnRoleFunctionNotesChanging(value);
					this.SendPropertyChanging();
					this._RoleFunctionNotes = value;
					this.SendPropertyChanged("RoleFunctionNotes");
					this.OnRoleFunctionNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChildrenRole", DbType="Bit NOT NULL")]
		public bool IsChildrenRole
		{
			get
			{
				return this._IsChildrenRole;
			}
			set
			{
				if ((this._IsChildrenRole != value))
				{
					this.OnIsChildrenRoleChanging(value);
					this.SendPropertyChanging();
					this._IsChildrenRole = value;
					this.SendPropertyChanged("IsChildrenRole");
					this.OnIsChildrenRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this.OnIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsDelete = value;
					this.SendPropertyChanged("IsDelete");
					this.OnIsDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorID", DbType="Int NOT NULL")]
		public int OperatorID
		{
			get
			{
				return this._OperatorID;
			}
			set
			{
				if ((this._OperatorID != value))
				{
					this.OnOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._OperatorID = value;
					this.SendPropertyChanged("OperatorID");
					this.OnOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OperatorName
		{
			get
			{
				return this._OperatorName;
			}
			set
			{
				if ((this._OperatorName != value))
				{
					this.OnOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._OperatorName = value;
					this.SendPropertyChanged("OperatorName");
					this.OnOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperateDate", DbType="Date NOT NULL")]
		public System.DateTime OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this.OnOperateDateChanging(value);
					this.SendPropertyChanging();
					this._OperateDate = value;
					this.SendPropertyChanged("OperateDate");
					this.OnOperateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Module")]
	public partial class T_Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleID;
		
		private int _ModuleParentID;
		
		private string _ModuleName;
		
		private string _ModuleNotes;
		
		private string _ModuleHierarchy;
		
		private int _ModulePriority;
		
		private string _RouteName;
		
		private bool _IsMenu;
		
		private bool _IsDelete;
		
		private int _OperatorID;
		
		private string _OperatorName;
		
		private System.DateTime _OperateDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIDChanging(int value);
    partial void OnModuleIDChanged();
    partial void OnModuleParentIDChanging(int value);
    partial void OnModuleParentIDChanged();
    partial void OnModuleNameChanging(string value);
    partial void OnModuleNameChanged();
    partial void OnModuleNotesChanging(string value);
    partial void OnModuleNotesChanged();
    partial void OnModuleHierarchyChanging(string value);
    partial void OnModuleHierarchyChanged();
    partial void OnModulePriorityChanging(int value);
    partial void OnModulePriorityChanged();
    partial void OnRouteNameChanging(string value);
    partial void OnRouteNameChanged();
    partial void OnIsMenuChanging(bool value);
    partial void OnIsMenuChanged();
    partial void OnIsDeleteChanging(bool value);
    partial void OnIsDeleteChanged();
    partial void OnOperatorIDChanging(int value);
    partial void OnOperatorIDChanged();
    partial void OnOperatorNameChanging(string value);
    partial void OnOperatorNameChanged();
    partial void OnOperateDateChanging(System.DateTime value);
    partial void OnOperateDateChanged();
    #endregion
		
		public T_Module()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleParentID", DbType="Int NOT NULL")]
		public int ModuleParentID
		{
			get
			{
				return this._ModuleParentID;
			}
			set
			{
				if ((this._ModuleParentID != value))
				{
					this.OnModuleParentIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleParentID = value;
					this.SendPropertyChanged("ModuleParentID");
					this.OnModuleParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ModuleName
		{
			get
			{
				return this._ModuleName;
			}
			set
			{
				if ((this._ModuleName != value))
				{
					this.OnModuleNameChanging(value);
					this.SendPropertyChanging();
					this._ModuleName = value;
					this.SendPropertyChanged("ModuleName");
					this.OnModuleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleNotes", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ModuleNotes
		{
			get
			{
				return this._ModuleNotes;
			}
			set
			{
				if ((this._ModuleNotes != value))
				{
					this.OnModuleNotesChanging(value);
					this.SendPropertyChanging();
					this._ModuleNotes = value;
					this.SendPropertyChanged("ModuleNotes");
					this.OnModuleNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleHierarchy", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ModuleHierarchy
		{
			get
			{
				return this._ModuleHierarchy;
			}
			set
			{
				if ((this._ModuleHierarchy != value))
				{
					this.OnModuleHierarchyChanging(value);
					this.SendPropertyChanging();
					this._ModuleHierarchy = value;
					this.SendPropertyChanged("ModuleHierarchy");
					this.OnModuleHierarchyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModulePriority", DbType="Int NOT NULL")]
		public int ModulePriority
		{
			get
			{
				return this._ModulePriority;
			}
			set
			{
				if ((this._ModulePriority != value))
				{
					this.OnModulePriorityChanging(value);
					this.SendPropertyChanging();
					this._ModulePriority = value;
					this.SendPropertyChanged("ModulePriority");
					this.OnModulePriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string RouteName
		{
			get
			{
				return this._RouteName;
			}
			set
			{
				if ((this._RouteName != value))
				{
					this.OnRouteNameChanging(value);
					this.SendPropertyChanging();
					this._RouteName = value;
					this.SendPropertyChanged("RouteName");
					this.OnRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMenu", DbType="Bit NOT NULL")]
		public bool IsMenu
		{
			get
			{
				return this._IsMenu;
			}
			set
			{
				if ((this._IsMenu != value))
				{
					this.OnIsMenuChanging(value);
					this.SendPropertyChanging();
					this._IsMenu = value;
					this.SendPropertyChanged("IsMenu");
					this.OnIsMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this.OnIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsDelete = value;
					this.SendPropertyChanged("IsDelete");
					this.OnIsDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorID", DbType="Int NOT NULL")]
		public int OperatorID
		{
			get
			{
				return this._OperatorID;
			}
			set
			{
				if ((this._OperatorID != value))
				{
					this.OnOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._OperatorID = value;
					this.SendPropertyChanged("OperatorID");
					this.OnOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OperatorName
		{
			get
			{
				return this._OperatorName;
			}
			set
			{
				if ((this._OperatorName != value))
				{
					this.OnOperatorNameChanging(value);
					this.SendPropertyChanging();
					this._OperatorName = value;
					this.SendPropertyChanged("OperatorName");
					this.OnOperatorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperateDate", DbType="Date NOT NULL")]
		public System.DateTime OperateDate
		{
			get
			{
				return this._OperateDate;
			}
			set
			{
				if ((this._OperateDate != value))
				{
					this.OnOperateDateChanging(value);
					this.SendPropertyChanging();
					this._OperateDate = value;
					this.SendPropertyChanged("OperateDate");
					this.OnOperateDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Department")]
	public partial class T_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DepNO;
		
		private int _SuitPeople;
		
		private string _DepName;
		
		private string _DepNickName;
		
		private int _DepTypeID;
		
		private string _DepType;
		
		private string _DepNotes;
		
		private bool _IsDelete;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDepNOChanging(string value);
    partial void OnDepNOChanged();
    partial void OnSuitPeopleChanging(int value);
    partial void OnSuitPeopleChanged();
    partial void OnDepNameChanging(string value);
    partial void OnDepNameChanged();
    partial void OnDepNickNameChanging(string value);
    partial void OnDepNickNameChanged();
    partial void OnDepTypeIDChanging(int value);
    partial void OnDepTypeIDChanged();
    partial void OnDepTypeChanging(string value);
    partial void OnDepTypeChanged();
    partial void OnDepNotesChanging(string value);
    partial void OnDepNotesChanged();
    partial void OnIsDeleteChanging(bool value);
    partial void OnIsDeleteChanged();
    #endregion
		
		public T_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNO", DbType="NVarChar(21) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DepNO
		{
			get
			{
				return this._DepNO;
			}
			set
			{
				if ((this._DepNO != value))
				{
					this.OnDepNOChanging(value);
					this.SendPropertyChanging();
					this._DepNO = value;
					this.SendPropertyChanged("DepNO");
					this.OnDepNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuitPeople", DbType="Int NOT NULL")]
		public int SuitPeople
		{
			get
			{
				return this._SuitPeople;
			}
			set
			{
				if ((this._SuitPeople != value))
				{
					this.OnSuitPeopleChanging(value);
					this.SendPropertyChanging();
					this._SuitPeople = value;
					this.SendPropertyChanged("SuitPeople");
					this.OnSuitPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepName", DbType="NVarChar(41) NOT NULL", CanBeNull=false)]
		public string DepName
		{
			get
			{
				return this._DepName;
			}
			set
			{
				if ((this._DepName != value))
				{
					this.OnDepNameChanging(value);
					this.SendPropertyChanging();
					this._DepName = value;
					this.SendPropertyChanged("DepName");
					this.OnDepNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNickName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DepNickName
		{
			get
			{
				return this._DepNickName;
			}
			set
			{
				if ((this._DepNickName != value))
				{
					this.OnDepNickNameChanging(value);
					this.SendPropertyChanging();
					this._DepNickName = value;
					this.SendPropertyChanged("DepNickName");
					this.OnDepNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepTypeID", DbType="Int NOT NULL")]
		public int DepTypeID
		{
			get
			{
				return this._DepTypeID;
			}
			set
			{
				if ((this._DepTypeID != value))
				{
					this.OnDepTypeIDChanging(value);
					this.SendPropertyChanging();
					this._DepTypeID = value;
					this.SendPropertyChanged("DepTypeID");
					this.OnDepTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepType", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DepType
		{
			get
			{
				return this._DepType;
			}
			set
			{
				if ((this._DepType != value))
				{
					this.OnDepTypeChanging(value);
					this.SendPropertyChanging();
					this._DepType = value;
					this.SendPropertyChanged("DepType");
					this.OnDepTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepNotes", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string DepNotes
		{
			get
			{
				return this._DepNotes;
			}
			set
			{
				if ((this._DepNotes != value))
				{
					this.OnDepNotesChanging(value);
					this.SendPropertyChanging();
					this._DepNotes = value;
					this.SendPropertyChanged("DepNotes");
					this.OnDepNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this.OnIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._IsDelete = value;
					this.SendPropertyChanged("IsDelete");
					this.OnIsDeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIC_PID")]
	public partial class DIC_PID : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pid_code;
		
		private System.Nullable<char> _class_code;
		
		private string _area_code;
		
		private string _pid_name;
		
		private string _pid_easycode;
		
		private System.Nullable<char> _pid_flag;
		
		private string _pid_opercode;
		
		private string _pid_cardtypeno;
		
		private System.Nullable<int> _pid_zkl;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpid_codeChanging(string value);
    partial void Onpid_codeChanged();
    partial void Onclass_codeChanging(System.Nullable<char> value);
    partial void Onclass_codeChanged();
    partial void Onarea_codeChanging(string value);
    partial void Onarea_codeChanged();
    partial void Onpid_nameChanging(string value);
    partial void Onpid_nameChanged();
    partial void Onpid_easycodeChanging(string value);
    partial void Onpid_easycodeChanged();
    partial void Onpid_flagChanging(System.Nullable<char> value);
    partial void Onpid_flagChanged();
    partial void Onpid_opercodeChanging(string value);
    partial void Onpid_opercodeChanged();
    partial void Onpid_cardtypenoChanging(string value);
    partial void Onpid_cardtypenoChanged();
    partial void Onpid_zklChanging(System.Nullable<int> value);
    partial void Onpid_zklChanged();
    #endregion
		
		public DIC_PID()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_code", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pid_code
		{
			get
			{
				return this._pid_code;
			}
			set
			{
				if ((this._pid_code != value))
				{
					this.Onpid_codeChanging(value);
					this.SendPropertyChanging();
					this._pid_code = value;
					this.SendPropertyChanged("pid_code");
					this.Onpid_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_code", DbType="Char(1)")]
		public System.Nullable<char> class_code
		{
			get
			{
				return this._class_code;
			}
			set
			{
				if ((this._class_code != value))
				{
					this.Onclass_codeChanging(value);
					this.SendPropertyChanging();
					this._class_code = value;
					this.SendPropertyChanged("class_code");
					this.Onclass_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_code", DbType="NVarChar(4)")]
		public string area_code
		{
			get
			{
				return this._area_code;
			}
			set
			{
				if ((this._area_code != value))
				{
					this.Onarea_codeChanging(value);
					this.SendPropertyChanging();
					this._area_code = value;
					this.SendPropertyChanged("area_code");
					this.Onarea_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_name", DbType="NVarChar(41)")]
		public string pid_name
		{
			get
			{
				return this._pid_name;
			}
			set
			{
				if ((this._pid_name != value))
				{
					this.Onpid_nameChanging(value);
					this.SendPropertyChanging();
					this._pid_name = value;
					this.SendPropertyChanged("pid_name");
					this.Onpid_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_easycode", DbType="NVarChar(11)")]
		public string pid_easycode
		{
			get
			{
				return this._pid_easycode;
			}
			set
			{
				if ((this._pid_easycode != value))
				{
					this.Onpid_easycodeChanging(value);
					this.SendPropertyChanging();
					this._pid_easycode = value;
					this.SendPropertyChanged("pid_easycode");
					this.Onpid_easycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_flag", DbType="Char(1)")]
		public System.Nullable<char> pid_flag
		{
			get
			{
				return this._pid_flag;
			}
			set
			{
				if ((this._pid_flag != value))
				{
					this.Onpid_flagChanging(value);
					this.SendPropertyChanging();
					this._pid_flag = value;
					this.SendPropertyChanged("pid_flag");
					this.Onpid_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_opercode", DbType="VarChar(4)")]
		public string pid_opercode
		{
			get
			{
				return this._pid_opercode;
			}
			set
			{
				if ((this._pid_opercode != value))
				{
					this.Onpid_opercodeChanging(value);
					this.SendPropertyChanging();
					this._pid_opercode = value;
					this.SendPropertyChanged("pid_opercode");
					this.Onpid_opercodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_cardtypeno", DbType="VarChar(4)")]
		public string pid_cardtypeno
		{
			get
			{
				return this._pid_cardtypeno;
			}
			set
			{
				if ((this._pid_cardtypeno != value))
				{
					this.Onpid_cardtypenoChanging(value);
					this.SendPropertyChanging();
					this._pid_cardtypeno = value;
					this.SendPropertyChanged("pid_cardtypeno");
					this.Onpid_cardtypenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_zkl", DbType="Int")]
		public System.Nullable<int> pid_zkl
		{
			get
			{
				return this._pid_zkl;
			}
			set
			{
				if ((this._pid_zkl != value))
				{
					this.Onpid_zklChanging(value);
					this.SendPropertyChanging();
					this._pid_zkl = value;
					this.SendPropertyChanged("pid_zkl");
					this.Onpid_zklChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
