<?xml version="1.0" encoding="utf-8"?><Database Name="WHSMPERSAUTH" Class="AuthMSLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=D:\VS2010\Myproject\Project\卢哥\ComPublishWeb_主平台_8_5\ComPublishWeb\App_Data\WHSMPERSAUTH.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="AuthMSModelsLibrary.Properties.Settings" SettingsPropertyName="WHSMPERSAUTHConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_UserRole" Member="T_UserRole">
    <Type Name="T_UserRole">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="OperateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_User" Member="T_User">
    <Type Name="T_User">
      <Column Name="UserID" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(31) NOT NULL" CanBeNull="false" />
      <Column Name="PID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IDNo" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="DepNO" Type="System.String" DbType="NVarChar(21) NOT NULL" CanBeNull="false" />
      <Column Name="DepSectionNO" Type="System.String" DbType="NVarChar(21)" CanBeNull="true" />
      <Column Name="SexNo" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CardNo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AccountNo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDCard" Type="System.String" DbType="NVarChar(21) NOT NULL" CanBeNull="false" />
      <Column Name="Flag" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_RoleModule" Member="T_RoleModule">
    <Type Name="T_RoleModule">
      <Column Name="ModuleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RightType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="OperateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_Role" Member="T_Role">
    <Type Name="T_Role">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RoleFunctionNotes" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsChildrenRole" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="OperateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_Module" Member="T_Module">
    <Type Name="T_Module">
      <Column Name="ModuleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModuleParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ModuleName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModuleNotes" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ModuleHierarchy" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModulePriority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RouteName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsMenu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OperatorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OperatorName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="OperateDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.T_Department" Member="T_Department">
    <Type Name="T_Department">
      <Column Name="DepNO" Type="System.String" DbType="NVarChar(21) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SuitPeople" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepName" Type="System.String" DbType="NVarChar(41) NOT NULL" CanBeNull="false" />
      <Column Name="DepNickName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DepTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DepNotes" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DIC_PID" Member="DIC_PID">
    <Type Name="DIC_PID">
      <Column Name="pid_code" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="class_code" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="area_code" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="pid_name" Type="System.String" DbType="NVarChar(41)" CanBeNull="true" />
      <Column Name="pid_easycode" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="pid_flag" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="pid_opercode" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="pid_cardtypeno" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="pid_zkl" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>