#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiGetMSModelsLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="COMPUB")]
	public partial class WebpageDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertWebPageSet(WebPageSet instance);
    partial void UpdateWebPageSet(WebPageSet instance);
    partial void DeleteWebPageSet(WebPageSet instance);
    partial void InsertWebPageUnits(WebPageUnits instance);
    partial void UpdateWebPageUnits(WebPageUnits instance);
    partial void DeleteWebPageUnits(WebPageUnits instance);
    partial void InsertAppUnits(AppUnits instance);
    partial void UpdateAppUnits(AppUnits instance);
    partial void DeleteAppUnits(AppUnits instance);
    #endregion
		
		public WebpageDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["COMPUBConnectionString"].ConnectionString, mappingSource)
        {
			OnCreated();
		}
		
		public WebpageDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebpageDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebpageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WebpageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WebPageSet> WebPageSet
		{
			get
			{
				return this.GetTable<WebPageSet>();
			}
		}
		
		public System.Data.Linq.Table<WebPageUnits> WebPageUnits
		{
			get
			{
				return this.GetTable<WebPageUnits>();
			}
		}
		
		public System.Data.Linq.Table<AppUnits> AppUnits
		{
			get
			{
				return this.GetTable<AppUnits>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebPageSet")]
	public partial class WebPageSet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pageno;
		
		private string _pagename;
		
		private string _pageshowscape;
		
		private string _descripte;
		
		private System.Nullable<bool> _iffrist;
		
		private string _layoutstyle;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpagenoChanging(int value);
    partial void OnpagenoChanged();
    partial void OnpagenameChanging(string value);
    partial void OnpagenameChanged();
    partial void OnpageshowscapeChanging(string value);
    partial void OnpageshowscapeChanged();
    partial void OndescripteChanging(string value);
    partial void OndescripteChanged();
    partial void OniffristChanging(System.Nullable<bool> value);
    partial void OniffristChanged();
    partial void OnlayoutstyleChanging(string value);
    partial void OnlayoutstyleChanged();
    #endregion
		
		public WebPageSet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pageno
		{
			get
			{
				return this._pageno;
			}
			set
			{
				if ((this._pageno != value))
				{
					this.OnpagenoChanging(value);
					this.SendPropertyChanging();
					this._pageno = value;
					this.SendPropertyChanged("pageno");
					this.OnpagenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagename", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pagename
		{
			get
			{
				return this._pagename;
			}
			set
			{
				if ((this._pagename != value))
				{
					this.OnpagenameChanging(value);
					this.SendPropertyChanging();
					this._pagename = value;
					this.SendPropertyChanged("pagename");
					this.OnpagenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageshowscape", DbType="NVarChar(50)")]
		public string pageshowscape
		{
			get
			{
				return this._pageshowscape;
			}
			set
			{
				if ((this._pageshowscape != value))
				{
					this.OnpageshowscapeChanging(value);
					this.SendPropertyChanging();
					this._pageshowscape = value;
					this.SendPropertyChanged("pageshowscape");
					this.OnpageshowscapeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripte", DbType="NVarChar(MAX)")]
		public string descripte
		{
			get
			{
				return this._descripte;
			}
			set
			{
				if ((this._descripte != value))
				{
					this.OndescripteChanging(value);
					this.SendPropertyChanging();
					this._descripte = value;
					this.SendPropertyChanged("descripte");
					this.OndescripteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iffrist", DbType="Bit")]
		public System.Nullable<bool> iffrist
		{
			get
			{
				return this._iffrist;
			}
			set
			{
				if ((this._iffrist != value))
				{
					this.OniffristChanging(value);
					this.SendPropertyChanging();
					this._iffrist = value;
					this.SendPropertyChanged("iffrist");
					this.OniffristChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_layoutstyle", DbType="NVarChar(50)")]
		public string layoutstyle
		{
			get
			{
				return this._layoutstyle;
			}
			set
			{
				if ((this._layoutstyle != value))
				{
					this.OnlayoutstyleChanging(value);
					this.SendPropertyChanging();
					this._layoutstyle = value;
					this.SendPropertyChanged("layoutstyle");
					this.OnlayoutstyleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WebPageUnits")]
	public partial class WebPageUnits : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _pageid;
		
		private int _pageunitid;
		
		private System.Nullable<bool> _ifloginshow;
		
		private string _showcontainer;
		
		private string _widgettype;
		
		private string _showtitle;
		
		private System.Nullable<int> _showorder;
		
		private string _specialCssFile;
		
		private string _UnitsTheparams;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpageidChanging(int value);
    partial void OnpageidChanged();
    partial void OnpageunitidChanging(int value);
    partial void OnpageunitidChanged();
    partial void OnifloginshowChanging(System.Nullable<bool> value);
    partial void OnifloginshowChanged();
    partial void OnshowcontainerChanging(string value);
    partial void OnshowcontainerChanged();
    partial void OnwidgettypeChanging(string value);
    partial void OnwidgettypeChanged();
    partial void OnshowtitleChanging(string value);
    partial void OnshowtitleChanged();
    partial void OnshoworderChanging(System.Nullable<int> value);
    partial void OnshoworderChanged();
    partial void OnspecialCssFileChanging(string value);
    partial void OnspecialCssFileChanged();
    partial void OnUnitsTheparamsChanging(string value);
    partial void OnUnitsTheparamsChanged();
    #endregion
		
		public WebPageUnits()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageid", DbType="Int NOT NULL")]
		public int pageid
		{
			get
			{
				return this._pageid;
			}
			set
			{
				if ((this._pageid != value))
				{
					this.OnpageidChanging(value);
					this.SendPropertyChanging();
					this._pageid = value;
					this.SendPropertyChanged("pageid");
					this.OnpageidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pageunitid", DbType="Int NOT NULL")]
		public int pageunitid
		{
			get
			{
				return this._pageunitid;
			}
			set
			{
				if ((this._pageunitid != value))
				{
					this.OnpageunitidChanging(value);
					this.SendPropertyChanging();
					this._pageunitid = value;
					this.SendPropertyChanged("pageunitid");
					this.OnpageunitidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifloginshow", DbType="Bit")]
		public System.Nullable<bool> ifloginshow
		{
			get
			{
				return this._ifloginshow;
			}
			set
			{
				if ((this._ifloginshow != value))
				{
					this.OnifloginshowChanging(value);
					this.SendPropertyChanging();
					this._ifloginshow = value;
					this.SendPropertyChanged("ifloginshow");
					this.OnifloginshowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showcontainer", DbType="NVarChar(50)")]
		public string showcontainer
		{
			get
			{
				return this._showcontainer;
			}
			set
			{
				if ((this._showcontainer != value))
				{
					this.OnshowcontainerChanging(value);
					this.SendPropertyChanging();
					this._showcontainer = value;
					this.SendPropertyChanged("showcontainer");
					this.OnshowcontainerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_widgettype", DbType="NVarChar(50)")]
		public string widgettype
		{
			get
			{
				return this._widgettype;
			}
			set
			{
				if ((this._widgettype != value))
				{
					this.OnwidgettypeChanging(value);
					this.SendPropertyChanging();
					this._widgettype = value;
					this.SendPropertyChanged("widgettype");
					this.OnwidgettypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showtitle", DbType="NVarChar(50)")]
		public string showtitle
		{
			get
			{
				return this._showtitle;
			}
			set
			{
				if ((this._showtitle != value))
				{
					this.OnshowtitleChanging(value);
					this.SendPropertyChanging();
					this._showtitle = value;
					this.SendPropertyChanged("showtitle");
					this.OnshowtitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showorder", DbType="Int")]
		public System.Nullable<int> showorder
		{
			get
			{
				return this._showorder;
			}
			set
			{
				if ((this._showorder != value))
				{
					this.OnshoworderChanging(value);
					this.SendPropertyChanging();
					this._showorder = value;
					this.SendPropertyChanged("showorder");
					this.OnshoworderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialCssFile", DbType="NVarChar(50)")]
		public string specialCssFile
		{
			get
			{
				return this._specialCssFile;
			}
			set
			{
				if ((this._specialCssFile != value))
				{
					this.OnspecialCssFileChanging(value);
					this.SendPropertyChanging();
					this._specialCssFile = value;
					this.SendPropertyChanged("specialCssFile");
					this.OnspecialCssFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitsTheparams", DbType="NVarChar(100)")]
		public string UnitsTheparams
		{
			get
			{
				return this._UnitsTheparams;
			}
			set
			{
				if ((this._UnitsTheparams != value))
				{
					this.OnUnitsTheparamsChanging(value);
					this.SendPropertyChanging();
					this._UnitsTheparams = value;
					this.SendPropertyChanged("UnitsTheparams");
					this.OnUnitsTheparamsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ApplicationUnits")]
	public partial class AppUnits : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _applicationid;
		
		private string _unitname;
		
		private System.Nullable<int> _datasourceid;
		
		private System.Nullable<int> _utype;
		
		private string _containUnits;
		
		private string _ucontent;
		
		private System.Nullable<int> _showstyleid;
		
		private System.Nullable<bool> _iseffictive;
		
		private System.Nullable<System.DateTime> _lastmodifytime;
		
		private System.Nullable<int> _NextUnit;
		
		private string _NextUnitShowType;
		
		private string _unitparams;
		
		private System.Nullable<int> _AuthErrorAlertUnit;
		
		private string _res2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnapplicationidChanging(int value);
    partial void OnapplicationidChanged();
    partial void OnunitnameChanging(string value);
    partial void OnunitnameChanged();
    partial void OndatasourceidChanging(System.Nullable<int> value);
    partial void OndatasourceidChanged();
    partial void OnutypeChanging(System.Nullable<int> value);
    partial void OnutypeChanged();
    partial void OncontainUnitsChanging(string value);
    partial void OncontainUnitsChanged();
    partial void OnucontentChanging(string value);
    partial void OnucontentChanged();
    partial void OnshowstyleidChanging(System.Nullable<int> value);
    partial void OnshowstyleidChanged();
    partial void OniseffictiveChanging(System.Nullable<bool> value);
    partial void OniseffictiveChanged();
    partial void OnlastmodifytimeChanging(System.Nullable<System.DateTime> value);
    partial void OnlastmodifytimeChanged();
    partial void OnNextUnitChanging(System.Nullable<int> value);
    partial void OnNextUnitChanged();
    partial void OnNextUnitShowTypeChanging(string value);
    partial void OnNextUnitShowTypeChanged();
    partial void OnunitparamsChanging(string value);
    partial void OnunitparamsChanged();
    partial void OnAuthErrorAlertUnitChanging(System.Nullable<int> value);
    partial void OnAuthErrorAlertUnitChanged();
    partial void Onres2Changing(string value);
    partial void Onres2Changed();
    #endregion
		
		public AppUnits()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applicationid", DbType="Int NOT NULL")]
		public int applicationid
		{
			get
			{
				return this._applicationid;
			}
			set
			{
				if ((this._applicationid != value))
				{
					this.OnapplicationidChanging(value);
					this.SendPropertyChanging();
					this._applicationid = value;
					this.SendPropertyChanged("applicationid");
					this.OnapplicationidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				if ((this._unitname != value))
				{
					this.OnunitnameChanging(value);
					this.SendPropertyChanging();
					this._unitname = value;
					this.SendPropertyChanged("unitname");
					this.OnunitnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datasourceid", DbType="Int")]
		public System.Nullable<int> datasourceid
		{
			get
			{
				return this._datasourceid;
			}
			set
			{
				if ((this._datasourceid != value))
				{
					this.OndatasourceidChanging(value);
					this.SendPropertyChanging();
					this._datasourceid = value;
					this.SendPropertyChanged("datasourceid");
					this.OndatasourceidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_utype", DbType="Int")]
		public System.Nullable<int> utype
		{
			get
			{
				return this._utype;
			}
			set
			{
				if ((this._utype != value))
				{
					this.OnutypeChanging(value);
					this.SendPropertyChanging();
					this._utype = value;
					this.SendPropertyChanged("utype");
					this.OnutypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_containUnits", DbType="NVarChar(50)")]
		public string containUnits
		{
			get
			{
				return this._containUnits;
			}
			set
			{
				if ((this._containUnits != value))
				{
					this.OncontainUnitsChanging(value);
					this.SendPropertyChanging();
					this._containUnits = value;
					this.SendPropertyChanged("containUnits");
					this.OncontainUnitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucontent", DbType="NVarChar(MAX)")]
		public string ucontent
		{
			get
			{
				return this._ucontent;
			}
			set
			{
				if ((this._ucontent != value))
				{
					this.OnucontentChanging(value);
					this.SendPropertyChanging();
					this._ucontent = value;
					this.SendPropertyChanged("ucontent");
					this.OnucontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_showstyleid", DbType="Int")]
		public System.Nullable<int> showstyleid
		{
			get
			{
				return this._showstyleid;
			}
			set
			{
				if ((this._showstyleid != value))
				{
					this.OnshowstyleidChanging(value);
					this.SendPropertyChanging();
					this._showstyleid = value;
					this.SendPropertyChanged("showstyleid");
					this.OnshowstyleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iseffictive", DbType="Bit")]
		public System.Nullable<bool> iseffictive
		{
			get
			{
				return this._iseffictive;
			}
			set
			{
				if ((this._iseffictive != value))
				{
					this.OniseffictiveChanging(value);
					this.SendPropertyChanging();
					this._iseffictive = value;
					this.SendPropertyChanged("iseffictive");
					this.OniseffictiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastmodifytime", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastmodifytime
		{
			get
			{
				return this._lastmodifytime;
			}
			set
			{
				if ((this._lastmodifytime != value))
				{
					this.OnlastmodifytimeChanging(value);
					this.SendPropertyChanging();
					this._lastmodifytime = value;
					this.SendPropertyChanged("lastmodifytime");
					this.OnlastmodifytimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextUnit", DbType="Int")]
		public System.Nullable<int> NextUnit
		{
			get
			{
				return this._NextUnit;
			}
			set
			{
				if ((this._NextUnit != value))
				{
					this.OnNextUnitChanging(value);
					this.SendPropertyChanging();
					this._NextUnit = value;
					this.SendPropertyChanged("NextUnit");
					this.OnNextUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextUnitShowType", DbType="NVarChar(20)")]
		public string NextUnitShowType
		{
			get
			{
				return this._NextUnitShowType;
			}
			set
			{
				if ((this._NextUnitShowType != value))
				{
					this.OnNextUnitShowTypeChanging(value);
					this.SendPropertyChanging();
					this._NextUnitShowType = value;
					this.SendPropertyChanged("NextUnitShowType");
					this.OnNextUnitShowTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitparams", DbType="NVarChar(100)")]
		public string unitparams
		{
			get
			{
				return this._unitparams;
			}
			set
			{
				if ((this._unitparams != value))
				{
					this.OnunitparamsChanging(value);
					this.SendPropertyChanging();
					this._unitparams = value;
					this.SendPropertyChanged("unitparams");
					this.OnunitparamsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthErrorAlertUnit", DbType="Int")]
		public System.Nullable<int> AuthErrorAlertUnit
		{
			get
			{
				return this._AuthErrorAlertUnit;
			}
			set
			{
				if ((this._AuthErrorAlertUnit != value))
				{
					this.OnAuthErrorAlertUnitChanging(value);
					this.SendPropertyChanging();
					this._AuthErrorAlertUnit = value;
					this.SendPropertyChanged("AuthErrorAlertUnit");
					this.OnAuthErrorAlertUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_res2", DbType="NChar(10)")]
		public string res2
		{
			get
			{
				return this._res2;
			}
			set
			{
				if ((this._res2 != value))
				{
					this.Onres2Changing(value);
					this.SendPropertyChanging();
					this._res2 = value;
					this.SendPropertyChanged("res2");
					this.Onres2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
